global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets:
          - localhost:9090
  - job_name: tempo
    static_configs:
      - targets:
          - ai-gateway-tempo.internal:3200
  - job_name: loki
    static_configs:
      - targets:
          - ai-gateway-loki.internal:3100
  - job_name: minio
    metrics_path: /minio/v2/metrics/cluster
    scheme: https
    static_configs:
      - targets:
          - ai-gateway-minio.internal:5532

storage:
  tsdb:
    out_of_order_time_window: 30m