global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets:
          - localhost:9090
  - job_name: tempo
    static_configs:
      - targets:
          - tempo:3200
  - job_name: loki
    static_configs:
      - targets:
          - loki:3100
  - job_name: minio
    metrics_path: /minio/v2/metrics/cluster
    scheme: https
    static_configs:
      - targets:
          - minio:5532
  - job_name: rockstar
    static_configs:
      - targets:
          - host.docker.internal:5679
